# Generated by Django 4.1.7 on 2023-04-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.AlterField(
            model_name='userorg',
            name='user',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
