# Generated by Django 4.1.7 on 2023-04-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_event_cost_alter_userorg_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorg',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.event', verbose_name='Выбери мероприятие'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.ticket', verbose_name='Доступные билеты для мероприятия'),
        ),
    ]
