# Generated by Django 4.1.7 on 2023-04-20 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_userorg_event_remove_event_tickets_event_tickets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name'], 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['name'], 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterModelOptions(
            name='userorg',
            options={'ordering': ['user'], 'verbose_name_plural': 'Пользователи'},
        ),
    ]
