# Generated by Django 4.2 on 2023-04-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('date_time', models.DateTimeField(null=True, verbose_name='Дата и время')),
                ('buration', models.IntegerField(null=True, verbose_name='Продолжительность')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('description_event', models.TextField(max_length=1000, null=True, verbose_name='Описание')),
                ('mini_description_event', models.TextField(max_length=100, null=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(null=True, upload_to='media', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organizer', models.CharField(max_length=1000, null=True, verbose_name='Название организации')),
                ('email_organizer', models.EmailField(max_length=254, null=True, verbose_name='Почта организатора')),
                ('number_phone_organizer', models.CharField(max_length=20, null=True, verbose_name='Номер организатора')),
            ],
            options={
                'verbose_name': 'Организаторы',
                'verbose_name_plural': 'Организаторы',
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_participants', models.CharField(max_length=100, null=True, verbose_name='ФИО')),
                ('age_participants', models.IntegerField(null=True, verbose_name='Возрост')),
                ('email_participants', models.EmailField(max_length=254, null=True, verbose_name='Почта участника')),
                ('number_phone_participants', models.CharField(max_length=20, null=True, verbose_name='Номер участника')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organizer.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Участники',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ticket', models.CharField(max_length=1000, verbose_name='Название')),
                ('description_ticket', models.TextField(max_length=100, null=True, verbose_name='Описание')),
                ('image_ticket', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('price_ticket', models.IntegerField(null=True, verbose_name='Цена')),
                ('email_participants', models.EmailField(max_length=254, null=True, verbose_name='Почта участника')),
                ('name_participants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organizer.participants', verbose_name='Имя участника')),
            ],
            options={
                'verbose_name': 'Билеты',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='Organizer',
            field=models.ForeignKey(max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organizer.organization', verbose_name='Организатор'),
        ),
    ]
