# Generated by Django 4.1.7 on 2023-04-20 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Название скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное кол-во использований скидки')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала действия скидки')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания действия скидки')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, зарегистрированный на мероприятие')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organizer.discount', verbose_name='Скидка, примененная к билету')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Номер телефона пользователя')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Адрес пользователя')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ссылка на стандартную модель пользователя')),
            ],
        ),
        migrations.RemoveField(
            model_name='participants',
            name='event',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='Organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='age',
        ),
        migrations.RemoveField(
            model_name='event',
            name='buration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mini_description_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='description_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='email_participants',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='image_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='name_participants',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='name_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price_ticket',
        ),
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Стоимость участия в мероприятии'),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='invoice_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Кол-во выставленных счетов на оплату билетов'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_count_access_to_talks',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Кол-во купленных билетов на доступ к докладам'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_count_access_to_workshops',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Кол-во купленных билетов на доступ к мастер-классам'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_count_online_streaming',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Кол-во купленных билетов на онлайн-трансляцию'),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(null=True, to='Organizer.ticket', verbose_name='Доступные билеты для мероприятия'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание билета'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_access_to_talks',
            field=models.BooleanField(default=False, null=True, verbose_name='Доступ к докладам'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_access_to_workshops',
            field=models.BooleanField(default=False, null=True, verbose_name='Доступ к мастер-классам'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_lunch',
            field=models.BooleanField(default=False, null=True, verbose_name='Доступ к обеду'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_online_streaming',
            field=models.BooleanField(default=False, null=True, verbose_name='Доступ к онлайн-трансляция'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название билета'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Цена билета'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tariff',
            field=models.CharField(max_length=50, null=True, verbose_name='Тариф билета'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organizer.event', verbose_name='Мероприятие, на которое зарегистрирован пользователь'),
        ),
        migrations.AddField(
            model_name='registration',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organizer.ticket', verbose_name='Билет, на который зарегистрирован пользователь'),
        ),
        migrations.AddField(
            model_name='discount',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organizer.ticket', verbose_name='Билет, к которому применяется скидка'),
        ),
    ]
