# Generated by Django 4.1.7 on 2023-04-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0002_discount_registration_user_remove_participants_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_user',
            field=models.IntegerField(default=0, null=True, verbose_name='Возраст пользователя'),
        ),
    ]
