# Generated by Django 4.1.7 on 2023-04-20 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0003_user_age_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='Ссылка на стандартную модель пользователя')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Номер телефона пользователя')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Адрес пользователя')),
                ('age_user', models.IntegerField(default=0, null=True, verbose_name='Возраст пользователя')),
            ],
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='event',
            name='invoice_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(to='Organizer.ticket', verbose_name='Доступные билеты для мероприятия'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='registration',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organizer.userorg', verbose_name='Пользователь, зарегистрированный на мероприятие'),
        ),
    ]
